/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    organizations: Organization;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * User first name
   */
  firstName: string;
  /**
   * User last name
   */
  lastName: string;
  /**
   * User profile picture
   */
  avatar?: (string | null) | Media;
  /**
   * User role in the system
   */
  role: 'student' | 'org-admin' | 'staff' | 'super-admin';
  /**
   * Organization the user belongs to (N:1 relationship)
   */
  organization?: (string | null) | Organization;
  /**
   * Student ID number (index number)
   */
  studentId?: string | null;
  /**
   * Short biography or description
   */
  bio?: string | null;
  /**
   * Phone number
   */
  phone?: string | null;
  /**
   * Faculty name
   */
  faculty?: string | null;
  /**
   * Field of study
   */
  fieldOfStudy?: string | null;
  /**
   * Current year of study
   */
  yearOfStudy?: number | null;
  /**
   * User interests and areas of focus
   */
  interests?:
    | {
        interest?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Notification preferences
   */
  notifications?: {
    /**
     * Receive email notifications
     */
    emailNotifications?: boolean | null;
    /**
     * Receive event reminders
     */
    eventReminders?: boolean | null;
    /**
     * Receive organization updates
     */
    organizationUpdates?: boolean | null;
  };
  /**
   * Account active status
   */
  isActive?: boolean | null;
  /**
   * Last login timestamp
   */
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  /**
   * Official name of the organization
   */
  name: string;
  /**
   * URL-friendly version of the name
   */
  slug: string;
  /**
   * Type of organization
   */
  type: 'scientific-circle' | 'student-organization' | 'faculty' | 'department' | 'student-government' | 'other';
  /**
   * Short description of the organization
   */
  description: string;
  /**
   * Detailed information about the organization
   */
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Organization logo
   */
  logo?: (string | null) | Media;
  /**
   * Cover image for organization page
   */
  coverImage?: (string | null) | Media;
  /**
   * Primary contact email
   */
  contactEmail?: string | null;
  /**
   * Contact phone number
   */
  contactPhone?: string | null;
  /**
   * Organization website URL
   */
  website?: string | null;
  /**
   * Social media profiles
   */
  socialMedia?: {
    /**
     * Facebook profile URL
     */
    facebook?: string | null;
    /**
     * Instagram profile URL
     */
    instagram?: string | null;
    /**
     * Twitter/X profile URL
     */
    twitter?: string | null;
    /**
     * LinkedIn profile URL
     */
    linkedin?: string | null;
    /**
     * YouTube channel URL
     */
    youtube?: string | null;
  };
  /**
   * Physical location details
   */
  location?: {
    /**
     * Building name or number
     */
    building?: string | null;
    /**
     * Room number
     */
    room?: string | null;
    /**
     * Full address
     */
    address?: string | null;
  };
  /**
   * Current status of the organization
   */
  status: 'active' | 'inactive' | 'pending' | 'suspended';
  /**
   * Year the organization was founded
   */
  foundedYear?: number | null;
  /**
   * Number of active members
   */
  memberCount?: number | null;
  /**
   * Tags for categorization and search
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Feature this organization on the homepage
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  /**
   * URL-friendly version of the title (e.g., "my-event")
   */
  slug: string;
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Organization hosting this event (N:1 relationship)
   */
  organization: string | Organization;
  /**
   * Date and time of the event
   */
  eventDate: string;
  /**
   * End date and time (for multi-day events)
   */
  endDate?: string | null;
  /**
   * Event location
   */
  location?: string | null;
  /**
   * Detailed location information
   */
  locationDetails?: {
    /**
     * Building name or number
     */
    building?: string | null;
    /**
     * Room number
     */
    room?: string | null;
    /**
     * Full address
     */
    address?: string | null;
    /**
     * Is this an online event?
     */
    isOnline?: boolean | null;
    /**
     * Link for online event (e.g., Zoom, Teams)
     */
    onlineLink?: string | null;
  };
  /**
   * Featured image for the event
   */
  image?: (string | null) | Media;
  /**
   * Additional images for the event
   */
  gallery?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Event category
   */
  category: 'workshop' | 'conference' | 'seminar' | 'social' | 'competition' | 'meeting' | 'other';
  /**
   * Maximum number of participants
   */
  capacity?: number | null;
  /**
   * Number of registered participants
   */
  registeredCount?: number | null;
  /**
   * Is registration required for this event?
   */
  registrationRequired?: boolean | null;
  /**
   * Registration deadline
   */
  registrationDeadline?: string | null;
  /**
   * External registration link
   */
  registrationLink?: string | null;
  /**
   * Current event status
   */
  status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled';
  /**
   * Feature this event on the homepage
   */
  featured?: boolean | null;
  /**
   * Tags for categorization and search
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Event organizers
   */
  organizers?:
    | {
        organizer?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  /**
   * Event sponsors
   */
  sponsors?:
    | {
        name?: string | null;
        logo?: (string | null) | Media;
        website?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  avatar?: T;
  role?: T;
  organization?: T;
  studentId?: T;
  bio?: T;
  phone?: T;
  faculty?: T;
  fieldOfStudy?: T;
  yearOfStudy?: T;
  interests?:
    | T
    | {
        interest?: T;
        id?: T;
      };
  notifications?:
    | T
    | {
        emailNotifications?: T;
        eventReminders?: T;
        organizationUpdates?: T;
      };
  isActive?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  organization?: T;
  eventDate?: T;
  endDate?: T;
  location?: T;
  locationDetails?:
    | T
    | {
        building?: T;
        room?: T;
        address?: T;
        isOnline?: T;
        onlineLink?: T;
      };
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  capacity?: T;
  registeredCount?: T;
  registrationRequired?: T;
  registrationDeadline?: T;
  registrationLink?: T;
  status?: T;
  featured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  organizers?:
    | T
    | {
        organizer?: T;
        id?: T;
      };
  sponsors?:
    | T
    | {
        name?: T;
        logo?: T;
        website?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  fullDescription?: T;
  logo?: T;
  coverImage?: T;
  contactEmail?: T;
  contactPhone?: T;
  website?: T;
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        linkedin?: T;
        youtube?: T;
      };
  location?:
    | T
    | {
        building?: T;
        room?: T;
        address?: T;
      };
  status?: T;
  foundedYear?: T;
  memberCount?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}